version: '3.8'

services:
  development_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barangay_db
      MYSQL_USER: bms
      MYSQL_PASSWORD: bms123
    ports:
      - '3306:3306'
